[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  publish = "dist"
  framework = "vite"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 